sudo: required

dist: trusty

language: node_js

node_js:
  - '10'

cache:
  directories:
    - node_modules

script:
  - yarn prettier:check
  - yarn lint
  - yarn test
  - yarn build

after_success:
  - yarn coveralls
